wget https://arbfonts.com//wp-content/fonts/diwany-arabic-fonts//mcs-diwany-jaly-s-u.ttf -O fonts/01.ttf
wget https://arbfonts.com//wp-content/fonts/new-arabic-fonts//46-Diwani-Bent.ttf -O fonts/02.ttf
wget https://arbfonts.com//wp-content/fonts/diwany-arabic-fonts//diwany-edited.ttf -O fonts/03.ttf
wget https://arbfonts.com/wp-content/fonts/diwany-arabic-fonts//arbfonts-samt-7017.ttf -O fonts/04.ttf
wget https://arbfonts.com//wp-content/fonts/kufi-arabic-fonts//QadasiRegular.ttf -O fonts/05.ttf
wget https://arbfonts.com//wp-content/fonts/kufi-arabic-fonts//Spirit-Of-Doha-Black.otf -O fonts/06.ttf
wget https://arbfonts.com//wp-content/fonts/new-arabic-fonts//AlQalam-alavi.ttf -O fonts/07.ttf
wget https://arbfonts.com//wp-content/fonts/new-arabic-fonts//22-andlso.ttf -O fonts/08.ttf
wget https://arbfonts.com//wp-content/fonts/new-arabic-fonts//ArefRuqaa-Bold-1.ttf -O fonts/09.ttf 
wget https://arbfonts.com//wp-content/fonts/new-arabic-fonts//ArefRuqaa-Regular-1.ttf -O fonts/10.ttf
wget https://arbfonts.com//wp-content/fonts/new-arabic-fonts//117-Barada-Reqa.ttf -O fonts/11.ttf
wget https://arbfonts.com/wp-content/fonts/diwany-arabic-fonts//arbfonts-diwany-thuluth.ttf -O fonts/12.ttf
wget https://arbfonts.com//wp-content/fonts/unlimited-free-arabic-fonts//UthmanicHafs1-Ver09_2.otf -O fonts/13.ttf
wget https://arbfonts.com//wp-content/fonts/new-arabic-fonts//ALAMERAH-Thin.ttf -O fonts/14.ttf
wget https://arbfonts.com/font_files/horr/unicode/Boahmed%20Alhour.ttf -O fonts/15.ttf
wget https://arbfonts.com//wp-content/fonts/misc//K-Kamran.ttf -O fonts/16.ttf
wget https://arbfonts.com//wp-content/fonts/farsi-free-fonts//Jamil-nory.ttf -O fonts/17.ttf
wget https://arbfonts.com//wp-content/fonts/brands-arasbic-fonts//Mobily.ttf -O fonts/18.ttf
wget https://arbfonts.com//wp-content/fonts/new-arabic-fonts//QTSManga-Regular-1.ttf -O fonts/19.ttf
wget https://arbfonts.com//wp-content/fonts/arabic-fonts/new//Al-Jazeera-Arabic-Regular.ttf -O fonts/20.ttf